import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wybierz typ <a href="">Generowania</a>
        </h1>
        <div>
          <ul>
            <li>
              <a href={"/isr"}>ISR</a>
            </li>
            <li>
              <a href={"/ssg"}>SSG</a>
            </li>
            <li>
              <a href={"/ssr"}>SSR</a>
            </li>
            <li>
              <a href={"/csr"}>CSR</a>
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
}
